### ISSUE TITLE
AccessToken再取得(RefreshToken利用)について

### ISSUE THREAD

**Issue by shota** [freee/freee-accounting-sdk-php#30]
**機能リクエストによって解決したい問題**
Refresh Tokenの使用は、[freee内のドキュメント](https://support.freee.co.jp/hc/ja/articles/115000145263-freee-API%E3%81%AE%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B)にて記載されているが、このAPIを利用するにあたって、非常に共通するユースケースなので、何かしらサポートがほしいなと思っています。
（バッチ処理する場合は事実上必須）

**上記の問題の解決策**
上記アクションを行うようなstatic関数をSocialiteProvidersで生成されたクラスに追加する対応になると思います。
どこかに簡単なドキュメントが追記されたほうが汎用的なユースケースに対応できるのかなと。

**Comment by dzeyelid** [comment]
@shota issue のご報告ありがとうございます！応答が遅れてしまい大変申し訳ございません。
おって、対応を検討してまいります。
